export const CREATE_RECOLHA = "CREATE_RECOLHA";

export const RETRIEVE_RECOLHAS = "RETRIEVE_RECOLHAS";

export const UPDATE_RECOLHA = "UPDATE_RECOLHA";

export const DELETE_RECOLHA = "DELETE_RECOLHA";