export const CREATE_RESULTADO = "CREATE_RESULTADO";

export const RETRIEVE_RESULTADOS = "RETRIEVE_RESULTADOS";

export const UPDATE_RESULTADO = "UPDATE_RESULTADO";

export const DELETE_RESULTADO = "DELETE_RESULTADO";